apiVersion: v1
kind: Secret
metadata:
  name: fortune-https
type: Opaque
data:
  foo: YmFyCg==
  https.cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrVENDQWVHZ0F3SUJBZ0lKQU9uM1NOZThwcE9yTUEwR0NTcUdTSWIzRFFFQkN3VUFNQk14RVRBUEJnTlYKQkFNTUNHSnZiM1J6ZEhKd01CNFhEVEU0TURZd05UQTVNekExTkZvWERUSTRNRFl3TWpBNU16QTFORm93RXpFUgpNQThHQTFVRUF3d0lZbTl2ZEhOMGNuQXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCCkFRQzZ5SlVBdWErd1QyenFyVzBmSkdWZmFhc2tDdDRDMEE0cVkxdU1IT210SlZubXZ1R3FKbGJFVUlrZlVhckgKNDA0QlU1bmcwbFRhdWlUT3FxNlRMQjFyTmhLYmlmS3JrOGtJOFlBdHhIUWZCSkdkL08yVld6aTNCU1djNzdDYwppK0hZcTNsbzlocW9aYkFibTIzU1o0Qnk5c0I1NWIvaDlGVFkvVU44YzRRbjZHajhEa0RVaTZUdmRWdG9lMXRTCit3M2VJc1lBeHNIUzVYNlFCS1ozc2VIaTlTNFJQblFWc1k1MU8zNmhWdlVyakpNNDh0THE1MDg0ckQyQjdLdSsKdXFxZ0ZtRWY4RzhDQ0k3NUNJUUNIK2JPRnBQSFU4WGxaekJPVkJCUmRTVkczT0N4OWl1Y0hYS3E5cGRFVnVIRQpoV0FNcEpJZUZCdUpneTNldHhFeDNRUkJBZ01CQUFHalVEQk9NQjBHQTFVZERnUVdCQlFJTHl4VHg3TE5Ka2IyCldCaCtlc2c4MjVvY3NEQWZCZ05WSFNNRUdEQVdnQlFJTHl4VHg3TE5Ka2IyV0JoK2VzZzgyNW9jc0RBTUJnTlYKSFJNRUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDQ3lQYS9CaitsM3RUOXdTTnJxd3F0MTkrMwp3VHkvWnZSTWhsRDhndFNleHdLcXZ2ZjdlNkRsdGd4VGxvSkhMdDdKRDN5NFlvZVNQM1UvUFFRd2s5LzVXOG1BClhRRm8xMFZJcEpzWWtnNVJVNUZlUC9HVnY3LzN1ZkM5eEJDOVdzZGdpOHpLaStScFNLWVI1NWw0NVlsWHZCQXUKd2dMWVdwcFV2OVlsaU9CMlM0V3N2aVRvbGEzRGFYdkFoQjJ5aDJLN1h6WlJuS1FrRnpKZmE4bUFyU3NwdlBBUwp3aGUxQkk2RHhjSkF5cmFhbEE0dlpTNE9ER3A5MjdFVHFaOW5Mb2hPeW5EV1haUGxPMDVmNTIyQzNqZWFOWlUxCkgxK1VPSXUySTU3Q1hIaFB6S3FJNVZyUlB5S3ZLTEsyeUFGRjFVSkVLQ25XL3dSNzFqL01TeVQ1NFF3eAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  https.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdXNpVkFMbXZzRTlzNnExdEh5UmxYMm1ySkFyZUF0QU9LbU5iakJ6cHJTVlo1cjdoCnFpWld4RkNKSDFHcXgrTk9BVk9aNE5KVTJyb2t6cXF1a3l3ZGF6WVNtNG55cTVQSkNQR0FMY1IwSHdTUm5menQKbFZzNHR3VWxuTyt3bkl2aDJLdDVhUFlhcUdXd0c1dHQwbWVBY3ZiQWVlVy80ZlJVMlAxRGZIT0VKK2hvL0E1QQoxSXVrNzNWYmFIdGJVdnNOM2lMR0FNYkIwdVYra0FTbWQ3SGg0dlV1RVQ1MEZiR09kVHQrb1ZiMUs0eVRPUExTCjZ1ZFBPS3c5Z2V5cnZycXFvQlpoSC9CdkFnaU8rUWlFQWgvbXpoYVR4MVBGNVdjd1RsUVFVWFVsUnR6Z3NmWXIKbkIxeXF2YVhSRmJoeElWZ0RLU1NIaFFiaVlNdDNyY1JNZDBFUVFJREFRQUJBb0lCQUI3TTZyMDI0WURLYUNSKwp1cXJTL3FCd05WZDVMMGo1ZEF5TFc5Sk1Ca0NXRXpBWXMrK3g2TWJ3bk52OFJKUTNxR3BSbGVOYjY4QXh4OVlJCmtVY1ZsRGhVcjFiVXRaNlRmU2dyWXI2cFVaaTMwU2RqU081REg2UVdoakJOMmlyR2FsU25XaHJ6MGt1SWtUVE0KT1p6amttdml3clNYTFVBZVlVdHk0QWtLcDNWSTlxRHZsUEVxL3RGQUxmcjRSSjR6VVdOY0Vvb2RUZ0FWYStiUgpEL3oxc3JrUHJKWUVmaXR3NjlTdmRGYUFnaHZ1UExBSG1Na1RuUmJ5YVU4S0ZzdTBBU3JwbWlOK2pyK0YzZXgxCkdCMEQ4elZRTm1JZWgzcDlvWDJ4aUZvcmFDVER6L05iNDMvVHA5M29vS1AzQXlBNkkvN1M5OWZFYU4vdjJnL3AKUW1xS3BWRUNnWUVBNStFa0NZbnB6RnA2MDBkeXNvVDNkckdmU2lMcU5WYU51amJpT1FheVNSNEFoRFloNkg3dQp1YXRGcDROcHFrMmRadVdrckgzNDBmUEhGN2lLOXRPUTNpM24zWkNLVTQzellQUjZ2TVVTc25Ga1JmRUhwSmFjClQvRFl5QTZNaWF0YnNJV2xNTWcrKy9TanMxNlhUTEFFZEZFcmo5V3FoanViaFVSWnhRWUM0S1VDZ1lFQXpqYU4KNGJZaHBTQUJjWHE4V0dVMzRXV3BwZTdIV0ZDVW1Wa2lwVFFJTkFFN3NJVUdzejZwZEZ6cWhFZWZQNkRWZE9aegpXRjVJWWZlRVgrZzgrRkVmWnduRTFzWnBFQUtUeUkyTENtUnhuVGxrRVpEcWtUd1ppNzRoSmFMVUZoaUlaV3VqCm02Mmg0RTB1NVFVOUNLQk9VVGJMakFseFhJbndDMWQxL3lwSmhtMENnWUVBbC9JWFRFemNNTFhsb0lkRUtLa3IKQTlOVy94eXIvckd1QTZVdFRwTU54dzNxNXJnV05pVGZTRGxzVmwydG94UmpIV2RFSm1nUjRYcHVMeVFWbzdKMQpUcklrS3pNcEFhR1dKeVZ0UEQramhkejZDVDd0ZERQaFVCMFI0TjV2eDFMTHJYdVdDTVpmUjNsQ3dDb3UyT2pLCnNuSHlLcm1ubVhoNzY3TWpaQkVSVjZVQ2dZQmlPWWd4dUdDa1YrOTREMStCdDR6N2wwSk00TVVob3hoMVJ3a0MKcWhzeU1sZ3RSK0FlSnozdVNJZ0l4Rmp0cFAyb05sRkJDWC91OGtpaXFtdklXRlBkNzhCTUVheGZ6T3A2QURuMwpsRXF0K25WWkRLOCt5T0xlTm8xeGNQTVhKMDVwQ1BHZ3FQOVBhVlJxRUttMjN5ME84RXZhZzNEMUJGdEwrN2dmCitCT1hyUUtCZ1FEQlg5aWRsNS94MkdEUDgwaXEwSkxBdG13N2FIbFVoK0lZZS9vL3Azbnd2MGFMbkVUQ2hXZ0sKSzd4RjBsR2lDN09lNUI1a09GWjVESTAwb1NBRWRldEJGc2dlTU0zZHFma2JnS0pEZFBrYlBMb0NscXBPK2crZQpSald3ZXZqaVd3MmpSSFREQlhzWWxiUi9HNUtvL1I3d2xERytFSnlEZUVtVFU5ZkJWSjhyeVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=


---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: fortune-config
data:
  interval: "10"           
  nginx-override-config.conf: |
    server {
      listen              80;
      listen              443 ssl;
      server_name         www.kubia-example.com;

      ssl_certificate     certs/https.cert;
      ssl_certificate_key certs/https.key;
      ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;

      gzip off;                                       
      gzip_types text/plain application/xml;         

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fortune-dep
spec:
  selector:
    matchLabels:
      app: nginx-fortune
  template:
    metadata:
      labels:
        app: nginx-fortune
    spec:
        containers:
        - name: fortune-html-producer
          image: sorididim11/fortune:1.0
          imagePullPolicy: Always
          env:
            - name: INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: fortune-config
                  key: interval
          command: ["/bin/fortune.sh"]
          args: ["2"]
          volumeMounts:
            - name: html
              mountPath: /var/htdocs
        - name: nginx-html-comsumer
          image: nginx
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: yes
            - name: certs-secret
              mountPath: /etc/nginx/certs/
              readOnly: true
          ports:
            - containerPort: 80
            - containerPort: 443
        volumes:
          - name: html
            emptyDir: {}
          - name: nginx-config
            configMap:
              name: fortune-config
              items: 
              - key: nginx-override-config.conf
                path: gzip.conf
          - name: certs-secret
            secret:
              secretName: fortune-https
               