apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzb3JpZGlkaW0xMSIsInBhc3N3b3JkIjoiUmxhd2hkcmpzMkAiLCJlbWFpbCI6InNvcmlkaWRpbTExQGdtYWlsLmNvbSIsImF1dGgiOiJjMjl5YVdScFpHbHRNVEU2VW14aGQyaGtjbXB6TWtBPSJ9fX0=
kind: Secret
metadata:
  name: mydocker-creds
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marathon-ee-dep
spec:
  selector:
    matchLabels:
      app: marathon-ee
  template:
    metadata:
      labels:
        app: marathon-ee
    spec:
        imagePullSecrets:
        - name: mydocker-creds
        containers:
        - name: marathon-ee
          image: sorididim11/marathon-dcos-ee:v1.4.7_1.9.8