apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vol-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vol
  template:
    metadata:
      labels:
        app: azure-vol 
    spec:
      containers:
      - name: web
        image: mongo
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc