
---
- hosts: all
  gather_facts: False
  tasks:
    - name: ensure firewalld is stoped and disabled
      service:
        name: firewalld
        enabled: no
        state: stopped


- include: util-redhat-subscription.yml
# - include: util-config-ohmyzsh.yml

- include: cluster.yml
