# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: quay.io/prometheus/node-exporter
  tag: v0.15.2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 9100
  containerPort: 9100

node:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 200Mi

dcgm:
  resources:
    limits:
      cpu: 400m
      memory: 200Mi
    requests:
      cpu: 400m
      memory: 200Mi

container:
  args:
  - --path.procfs=/host/proc
  - --path.sysfs=/host/sys
  - --collector.textfile.directory=/run/prometheus

  volumes:
  - name: proc
    hostPath:
      path: /proc
  - name: sys
    hostPath:
      path: /sys
  - name: collector-textfiles
    emptyDir:
      medium: Memory

  volumeMounts:
  - name: proc
    mountPath: /host/proc
    readOnly:  true
  - name: sys
    mountPath: /host/sys
    readOnly: true
  - name: collector-textfiles
    mountPath: /run/prometheus
    readOnly: true
## Tolerations for use with node taints
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations:
- effect: NoSchedule
  operator: Exists

## Node Selector to constrain pods to run on particular nodes
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
nodeSelector: []

## If true, create & use RBAC resources resp. Pod Security Policies
##
global:
  rbacEnable: true
  pspEnable: true
  
  # Reference to one or more secrets to be used when pulling images
  imagePullSecrets: []
  #  - name: "image-pull-secret"

# default rules are in templates/node.rules.yaml
# prometheusRules: {}

## Custom Labels to be added to ServiceMonitor
##
additionalServiceMonitorLabels: {}
##Custom Labels to be added to Prometheus Rules CRD
##
additionalRulesLabels: {}

# deploy node_exporter as a DaemonSet
enableDaemonSet: true
# for deployments that have node_exporter deployed outside of the cluster, list
# their addresses here
endpoints: []
nodeExporterPort: 9100
