
- hosts: kube-master[0]
  tasks:
  - name: delete secrets for datalake/edw properties"
    command: "{{ bin_dir }}/kubectl delete secret shh{{item}}"
    run_once: true  
    with_sequence: start=1 end=50 format=%03d