---
dependencies:
  - role: kubernetes-apps/external_provisioner/local_volume_provisioner
    when: local_volume_provisioner_enabled
    tags:
      - apps
      - local-volume-provisioner
      - external-provisioner
      
  - role: kubernetes-apps/external_provisioner/nfs-cli-provisiner
    when: nfs_cli_volume_provisioner_enabled
    tags:
      - apps
      - nfs-cli-volume-provisioner
      - external-provisioner

  - role: kubernetes-apps/external_provisioner/cephfs_provisioner
    when: cephfs_provisioner_enabled
    tags:
      - apps
      - cephfs-provisioner
      - external-provisioner

  - role: kubernetes-apps/external_provisioner/azure_provisioner
    when: 
      - cloud_provider is defined 
      - cloud_provider == "azure" 
      - azure_provisioner_enabled 
    tags:
      - apps
      - azure-provisioner
      - external-provisioner