apiVersion: v1
kind: LimitRange
metadata:
  name: example
spec:
  limits:
  - type: Pod                        
    min:                             
      cpu: 50m                       
      memory: 5Mi                    
    max:                             
      cpu: 1                         
      memory: 1Gi                    
  - type: Container                  
    defaultRequest:                  
      cpu: 100m                      
      memory: 10Mi                   
    default:                         
      cpu: 200m                      
      memory: 100Mi                  
    min:                             
      cpu: 50m                       
      memory: 5Mi                    
    max:                             
      cpu: 1                         
      memory: 1Gi                    
    maxLimitRequestRatio:            
      cpu: 4                         
      memory: 10                     
  - type: PersistentVolumeClaim      
    min:                             
      storage: 1Gi                   
    max:                             
      storage: 10Gi                  



# use default request and limit specified in limitrange
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-default
spec:
  containers:
  - image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    name: main

---
apiVersion: v1
kind: Pod
metadata:
  name: limited-pod
spec:
  containers:
  - image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    name: main
    resources:             
      limits:              
        cpu: 2        # it will be not allowd bacause it is bigger than limit range max      
        memory: 20Mi 

