apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: foo
  name: cpu-and-mem
spec:
  hard:
    requests.cpu: 200m
    requests.memory: 200Mi
    limits.cpu: 200m
    limits.memory: 500Mi
    pods: 5                                                   
    replicationcontrollers: 5                                     
    secrets: 10                                                   
    configmaps: 10                                                
    persistentvolumeclaims: 4                                     
    services: 5                                                   
    services.loadbalancers: 1                                     
    services.nodeports: 2                                         
    ssd.storageclass.storage.k8s.io/persistentvolumeclaims: 2     