
apiVersion: v1
kind: Service
metadata:
  name: cpu-deepo
spec:
  selector:
    app: cpu-deepo
  type: NodePort
  ports:
    - port: 8888
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-deepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-deepo
  template:
    metadata:
      labels:
        app: cpu-deepo
    spec:
      containers:
      - name: cpu-deep-container
        image: "ufoym/deepo:all-py36-jupyter-cpu"
        command: ["jupyter"]
        args: ["notebook", "--no-browser", "--allow-root", "--NotebookApp.token=", "--notebook-dir='/root'"]