
- hosts: kube-master[0]
  tasks:
  - name: generate secrets home DIR
    file:
      path: "{{ kube_config_dir }}/secrets"
      state: directory

  - name: create secret directory for each account"
    file:
      path: "{{ kube_config_dir }}/secrets/shh{{item}}"  
      state: directory
    with_sequence: start=1 end=50 format=%03d

  - name: generate secrets for datalake/edw
    template:
      src: "datalake.properties.j2"
      dest: "{{ kube_config_dir }}/secrets/shh{{item}}/datalake.properties"
    with_sequence: start=1 end=50 format=%03d

  - name: create secrets based on datalake/edw properties"
    command: "{{ bin_dir }}/kubectl create secret generic shh{{item}} --from-file {{ kube_config_dir }}/secrets/shh{{item}}/datalake.properties"  
    run_once: true  
    with_sequence: start=1 end=50 format=%03d
