apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-k8s-sc
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
