apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-secret
spec:
  selector:
    matchLabels:
      app: my-secret-app
  template:
    metadata:
      labels:
        app: my-secret-app
    spec:
      containers:
      - name: container1
        image: gcr.io/kuar-demo/kuard-amd64:1
        imagePullPolicy: Always
        command: 
          - "/kuard"
          - $(EXTRA_PARAM_FROM_CONFIGMAP)
        volumeMounts:
          - name: my-secret-volume
            mountPath: /tls
            readOnly: true
      volumes:
        - name: my-secret-volume
          secret:
            secretName: my-secret
              
