apiVersion: v1
kind: Pod
metadata:
  name: kuard-pod
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources:
      requests:
        cpu: "500m"
        memory: "50Mi"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
