apiVersion: v1
kind: Pod
metadata:
  name: kuard-pod
spec:
  volumes:
  - name: kuard-data
    hostPath:
      path: "/var/lib/kuard"
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    volumeMounts:
    - name: kuard-data
      mountPath: "/data"

    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
