apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec: 
  nodeSelector:
    gpu: "true"
  containers:
    - name: kubia
      image: luksa/kubia-unhealthy
      livenessProbe:
        httpGet:
          path: /
          port: 8080
