apiVersion: v1
kind: Service
metadata: 
  name: kubia-nodeport
spec:
  type: NodePort
  selector:
    app: kubia-pod
  ports:
    - name: node
      port: 80
      targetPort: 8080
      nodePort: 30001
  
