apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: kube-system
  name: ingress-kube-system
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    ingress.kubernetes.io/auth-secret: "{{ ingress_auth_secret_name }}"
    ingress.kubernetes.io/auth-realm: "Authentication Required - foo"
spec:
  rules:
  - host: dashboard.k8s.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 9090  
  - host: monitoring.k8s.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kube-prometheus-grafana
          servicePort: 80
  - host: logging.k8s.com
    http:
      paths:
      - backend:
          serviceName: kibana-logging
          servicePort: 5601
        path: /
  - host: registry.k8s.com
    http:
      paths:
      - backend:
          serviceName: registry
          servicePort: 5000
        path: /