apiVersion: v1
kind: Service
metadata:
  name: gpu-deepo
spec:
  type: NodePort
  selector:
    app: gpu-deepo
  ports:
    - port: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-deepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-deepo
  template:
    metadata:
      labels:
        app: gpu-deepo
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-02
      containers:
      - name: deep-container
        image: "ufoym/deepo:all-jupyter-py36-cu90"
        command: ["jupyter"]
        args: ["notebook", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=", "--notebook-dir='/root'"]
#        resources:
#          limits:
#            nvidia.com/gpu: 2 # requesting 2 GPUs
        volumeMounts:
          - name: vol1
            mountPath: /data
      volumes:
       - name: vol1
         hostPath:
           path: /data