apiVersion: v1
kind: Service
metadata:
  name: hobboy-cpu
spec:
  selector:
    app: hobby-cpu
  type: NodePort
  ports:
    - port: 8888
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobby-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hobby-cpu
  template:
    metadata:
      labels:
        app: hobby-cpu
    spec:
      containers:
      - name: hobby
        image: "sorididim11/hobby:cpu"
        args: [ "/run_jupyter.sh", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=hpinvent1!"]
        resources:
          requests:
            cpu: 1
            memory: 128Mi
          limits:
            cpu: 2
            memory: 256Mi