apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: kuard-rs
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: kurad
  template:
    metadata:
      labels:
        app: kurad
        version: "2"
    spec:
       containers:
         - name: kuard
           image: "gcr.io/kuar-demo/kuard-amd64:1"
