apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
spec:
#  selector:
#    app: kubia-pod
  replicas: 3 
  
  template:
    metadata:
      labels:
        app: kubia-pod
    spec:
      containers:
        - name: kubia-c
          image: luksa/kubia
          ports:
            - containerPort: 8080
