apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-rs
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubia-pod
  replicas: 3 
  
  template:
    metadata:
      labels:
        app: kubia-pod
    spec:
      containers:
        - name: kubia-c
          image: luksa/kubia
          ports:
            - containerPort: 8080
